keys:
 - &desk age1est4jdeu803qv6jng7vrj9x92l3xs0mr6qwv6fpt0p7tdd26xd6s84k2pq
 - &t440p age196cqwq7cfr20zhlxwdnjrtlnn4w3ay5q52wxec5pyk2ksvq3s9ms0qjzyr
 - &server age1w785k56chrrsc29jgkjzyvxfj3lx5sx56cm5fg6ldvychdga9umspddsfg
 - &vps age1gcexqg5gdd28ldwxszsx6x7cq2uhttr7dtdwfv60ncvvus7lmy8ss9krsy
creation_rules:
 - path_regex: hosts/server/secrets/[^/]+$
   key_groups:
   - age:
     - *desk
     - *t440p
     - *server
 - path_regex: hosts/vps/secrets/[^/]+$
   key_groups:
   - age:
     - *desk
     - *vps
     - *t440p
 - path_regex: certs/[^/]+$
   key_groups:
   - age:
     - *desk
     - *t440p
     - *server