name: build-hosts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  # push:
  workflow_dispatch:
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - uses: actions/checkout@v4
      - name: Lix Installer
        run: curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm --extra-conf "trusted-users = root runner"
      - uses: cachix/cachix-action@v16
        with:
          name: meow-servers
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build server
        run: nix build --accept-flake-config .#nixosConfigurations.server.config.system.build.toplevel
